/*
/// SOFT SKILLS ~ GENERAL ///

var softSkillsList = [
  "Time management",
  "Effective communication",
  "Teamwork",
  "Responsibility",
  "Creativity",
  "Problem-solving",
  "Leadership",
  "Extroversion",
  "People skills",
  "Openness",
  "Adaptability",
  "Emotional intelligence",
  "Conflict management",
  "Stress management",
  "Productivity & organization",
  "Critical thinking",
  "Attention to detail",
  "Patience",
  "Motivation",
  "Flexibility",
  "Drive",
  "Active Listening",
];

/// SOFT SKILLS ///

var adaptabilitySoftSkillsList = [
  "Self-management",
  "Optimism",
  "Calmness",
  "Analysis",
  "Self-motivation",
  "Resilient",
  "Leadership",
  "Decision-Making",
  "Conflict resolution",
  "Innovative",
  "Constant learning",
  "Collaborative",
  "Observant",
  "Tech savvy",
  "Open-minded",
  "Curious",
  "Organizational",
  "Emotional Intelligence",
  "Ability to Learn Quickly",
  "Attention to Detail",
  "Determined",
  "Delegating",
  "Analytical",
  "Positivity",
  "Empathetic",
  "Time Management",
  "Receptive to criticism",
  "Problem Solving",
  "Stress Management",
  "Resourcefulness",
];

var attentionToDetailSoftSkillsList = [
  "Scheduling",
  "Introspection",
  "Acuity",
  "Questioning",
  "Critical observation",
];

var communicationSoftSkillsList = [
  " Active listening",
  "Articulating",
  "Asking questions",
  "Assertiveness",
  "Body language",
  "Brainstorming",
  "Business Storytelling",
  "Clarity",
  "Collaboration",
  "Concision",
  "Confidence",
  "Conflict management",
  "Constructive feedback",
  "Content strategy",
  "Convincing",
  "Courteous",
  "Creative thinking",
  "Debating",
  "Describing ability",
  "Diplomacy",
  "Editing",
  "Emailing",
  "Emotional intelligence",
  "Empathy",
  "Explaining",
  "Expression",
  "Eye contact",
  "Facial expressions",
  "Friendliness",
  "Grammar",
  "Humour",
  "Imagination",
  "Improvisation",
  "Interpersonal",
  "Life Skills",
  "Listening",
  "Logical thinking",
  "Marketing",
  "Motivation",
  "Multilingual",
  "Negotiating",
  "Nonverbal Communication",
  "Open Mindedness",
  "Persuasive",
  "Presentation",
  "Promoting",
  "Public speaking",
  "Quick thinking",
  "Quotes",
  "Rapport building",
  "Reading body language",
  "Reading facial expressions",
  "Social",
  "Social media",
  "Speaking",
  "Speech writing",
  "Team Building",
  "Teamwork",
  "Technical Writing",
  "Telephone",
  "Verbal Communication",
  "Visualizing",
  "Vocabulary",
  "Vocal tone and pitch",
  "Writing",
  "Written Communication",
];

var computerSoftSkillsList = [
  "Presentation",
  "Word Processing",
  "Data Analytics",
  "Systems Administration",
];

var creativitySoftSkillsList = [
  "Imagination",
  "Mind-mapping",
  "Innovation",
  "Experimentation",
  "Questioning",
];

var leadershipSoftSkillsList = [
  "Management skills",
  "Authenticity",
  "Mentorship",
  "Generosity",
  "Cultural intelligence",
  "Feedback",
  "Responsibility",
  "Flexibility",
  "Commitment",
];

var lifeSoftSkillsList = [
  "Problem Solving",
  "Handling Criticism",
  "Adaptability",
  "Resilience",
];

var organizationSoftSkillsList = [
  "Decision-Making",
  "Time Management",
  "Delegation",
  "Communication",
  "Setting goals",
  "Working under pressure",
  "Self-motivation",
  "Analytical thinking",
  "Attention to detail",
  "Strategic planning",
  "Dedication",
  "Self-management",
  "Initiative",
  "Trustworthiness",
  "Coordination",
  "Integrity",
  "Dependability",
  "Stress management",
  "Scheduling",
];

var problemSolvingSoftSkillsList = [
  "Logical reasoning",
  "Observation",
  "Brainstorming",
  "Decision making",
  "Analytical skills",
  "Research skills",
  "Creativity",
  "Critical-thinking skills",
  "Collaboration",
  "Communication skills",
];

var socialSoftSkillsList = [
  "Empathy",
  "Humor",
  "Networking",
  "Tolerance",
  "Diplomacy",
  "Teamwork",
  "Patience",
  "Trustworthiness"
];

var teamworkSoftSkillsList = [
  "Conflict management",
  "Conflict resolution",
  "Collaboration",
  "Coordination",
  "Idea exchange",
  "Mediation",
  "Active listening",
  "Confidence",
  "Persuasion",
  "Patience",
  "Mediation",
  "Listening",
  "Diplomacy",
  "Communication",
  "Empathy",
  "Respect",
  "Negotiation",
  "Friendliness",
  "Idea exchange",
  "Facilitation",
];

var timeManagementSoftSkillsList = [
  "Prioritizing",
  "Planning",
  "Goal setting",
  "Asking for help",
  "Automating tasks",
  "Batching",
  "Clarity",
  "Completion",
  "Coping skills and Stress management",
  "Creating routines",
  "Discipline / Beating procrastination",
  "Staying flexible",
  "	Focusing",
  "Getting in the flow",
  "Problem-solving",
  "Punctuality",
  "Rest (recovery time)",
  "Setting up deadlines",
  "Avoiding perfectionism",
  "Delegation",
  "	Decision-making",
  "Multitasking",
  "Strategic thinking",
  "Strategic planning",
  "Scheduling",
  "Managing appointments",
  "Record keeping",
  "Organization and filing",
  "Meeting deadlines",
  "Self-awareness",
  "Effective teamwork",
  "Documentation",
  "Assessment and evaluation",
  "Office management and maintenance",
  "Stock inventory",
  "Resource management",
];

var workEthicSoftSkillsList = [
  "Responsibility",
  "Discipline",
  "Dependability",
  "Commitment",
  "Professionalism",
];*/
